version: "3.9"
services:
  db:
    # Use the official postgres:15 image
    image: postgres:15
    restart: always
    environment:
      # Set the password, username and database name
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: wiggle-paw
    volumes:
      # Map the local pgdata folder to the container's /var/lib/postgresql/data directory
      - ./pgdata:/var/lib/postgresql/data
    ports:
      # Expose port 6969 on the host to port 5432 in the container
      - "6969:5432"
  minio:
    # Use minio for local development storage (compatible with S3).
    # Production storage maybe other service like AWS S3, Cloudfare R2, etc.
    image: minio/minio:latest
    restart: always
    environment:
      MINIO_ROOT_USER: 'root'
      MINIO_ROOT_PASSWORD: 'password'
      MINIO_API_CORS_ALLOW_ORIGIN: '*'
    volumes:
      # Map the local storage folder to the container's /data/minio directory
      - ./s3-data:/data/minio
    ports:
      # Expose port 9003 on the host to port 9000 in the container.
      # This is for the minio server.
      - "9003:9000"
      # Expose port 9099 on the host to port 9090 in the container.
      # This is for the minio console.
      - "9099:9090"
    command: minio server /data/minio --console-address ":9090"
  minio-mc:
    # Use minio client to create a bucket for the minio server.
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        mc config host add minio http://minio:9000 root password;
        mc mb --quiet minio/wigglepaw;
        mc anonymous set download minio/wigglepaw;
      "

