name: "CI - Lint"
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - "src/**"
env:
  SKIP_ENV_VALIDATION: 1
permissions:
  checks: write
  contents: write
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.25.1
      - uses: actions/setup-node@v2
        with:
          node-version: 17.1.0
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts
      # - name: Run tests
      #   run: pnpm test
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          eslint_extensions: ts,tsx
          prettier: true
